### ISSUE TITLE
Add the ability to adjust speed / size / colors in Ledify

### ISSUE THREAD

**Issue by thibault** [thibault/Miximum-apps#2]

**Comment by PatrickB** [comment]
I did find it impossible to read at the default speed/size at 1 meter away.  However from 4 meters and further, the default speed/size is fine.  

Also, since red has the longest wavelength, it is more visible at a distance - just as the red of a traffic light can be seen further away than the green.  Having the option to change speed/size/color would be useful though.

**Comment by thibault** [comment]
I'm planning to implement a setting to adjust scrolling speed. As soon as I have enough free time…
